[book]
authors = ["Daniel Onyesoh", "Christian Schmitz"]
language = "en"
multilingual = false
src = "src"
title = "The Helios Smart Contract Language"

[build]
build-dir = "book"
create-missing = false

[output.html]
additional-js = ["src/custom.js"]
additional-css = ["src/custom.css"]
git-repository-url = "https://github.com/hyperion-bt/helios-book"
git-repository-icon = "fa-github"
site-url = "/"

[output.html.fold]
enable = true
level = 0

[preprocessor.main]
command = "node ./preprocess.js"
